import { useEffect, useMemo, useState } from 'react';
import { useRepositoryData } from '@/app/hooks';
import { useSettings } from '@/app/SettingsProvider';
import { Button, Field, IconButton, NumberInput, Segmented, Select } from '@/components/ui';
import { Icon, Icons } from '@/components/icons';
import { generateWarmup, type WarmupStep } from '@/domain/warmup';
import type { Equipment } from '@/domain/types';
import { formatWeight, toGrams } from '@/domain/units';

/**
 * Warm-up generator UI. Ramps are generated by domain/warmup.ts and then become an
 * editable draft — the user can change any load or rep count before inserting them.
 */
export function WarmupPanel({
  workingWeightG,
  equipment = 'barbell',
  onInsert,
  insertLabel = 'Insert warm-up sets',
}: {
  workingWeightG?: number;
  equipment?: Equipment;
  onInsert?: (steps: WarmupStep[]) => void;
  insertLabel?: string;
}) {
  const { settings, weightUnit } = useSettings();
  const { data } = useRepositoryData(
    async (repository) => ({
      bars: await repository.listBarProfiles(),
      inventories: await repository.listPlateInventories(),
    }),
    [],
  );

  // Memoised so the empty-array fallbacks do not create new effect dependencies each render.
  const bars = useMemo(() => data?.bars ?? [], [data]);
  const inventories = useMemo(() => data?.inventories ?? [], [data]);

  const isBarbell = equipment === 'barbell' || equipment === 'smith machine';
  const [mode, setMode] = useState<'barbell' | 'increment'>(isBarbell ? 'barbell' : 'increment');
  const [setCount, setSetCount] = useState<'3' | '4' | '5'>('4');
  const [barId, setBarId] = useState('');
  const [inventoryId, setInventoryId] = useState('');
  const [incrementText, setIncrementText] = useState(weightUnit === 'kg' ? '2.5' : '5');
  const [workingText, setWorkingText] = useState(() =>
    workingWeightG ? formatWeight(workingWeightG, weightUnit) : '',
  );
  const [draft, setDraft] = useState<WarmupStep[] | null>(null);

  useEffect(() => {
    if (!barId && bars.length > 0) {
      setBarId(
        settings.defaultBarProfileId ?? bars.find((bar) => bar.isDefault)?.id ?? bars[0]!.id,
      );
    }
    if (!inventoryId && inventories.length > 0) {
      setInventoryId(
        settings.defaultPlateInventoryId ??
          inventories.find((entry) => entry.isDefault)?.id ??
          inventories[0]!.id,
      );
    }
  }, [
    bars,
    inventories,
    barId,
    inventoryId,
    settings.defaultBarProfileId,
    settings.defaultPlateInventoryId,
  ]);

  const workingG = useMemo(() => {
    const value = Number.parseFloat(workingText.replace(',', '.'));
    return Number.isFinite(value) ? toGrams(value, weightUnit) : 0;
  }, [workingText, weightUnit]);

  const generated = useMemo(() => {
    if (workingG <= 0) return [];
    const count = Number(setCount) as 3 | 4 | 5;
    if (mode === 'barbell') {
      const bar = bars.find((entry) => entry.id === barId);
      const inventory = inventories.find((entry) => entry.id === inventoryId);
      if (!bar || !inventory) return [];
      return generateWarmup({
        kind: 'barbell',
        workingWeightG: workingG,
        barWeightG: bar.weightG,
        collarWeightG: bar.collarWeightG,
        plates: inventory.plates,
        setCount: count,
      });
    }
    const increment = toGrams(
      Number.parseFloat(incrementText.replace(',', '.')) || 2.5,
      weightUnit,
    );
    return generateWarmup({
      kind: 'increment',
      workingWeightG: workingG,
      incrementG: increment,
      setCount: count,
    });
  }, [mode, workingG, setCount, bars, barId, inventories, inventoryId, incrementText, weightUnit]);

  // Regenerating replaces the draft; editing after that keeps the user's changes.
  useEffect(() => {
    setDraft(null);
  }, [generated]);

  const steps = draft ?? generated;

  const updateStep = (index: number, patch: Partial<WarmupStep>) => {
    setDraft((current) => {
      const base = current ?? generated;
      return base.map((step, i) => (i === index ? { ...step, ...patch } : step));
    });
  };

  const removeStep = (index: number) => {
    setDraft((current) => (current ?? generated).filter((_, i) => i !== index));
  };

  return (
    <div>
      <Field label={`Working weight (${weightUnit})`}>
        {({ id }) => (
          <NumberInput
            id={id}
            data-autofocus
            value={workingText}
            step="any"
            min={0}
            onChange={(event) => setWorkingText(event.target.value)}
            placeholder={weightUnit === 'kg' ? '100' : '225'}
          />
        )}
      </Field>

      <div className="mb-4">
        <span className="rf-label">Equipment</span>
        <Segmented
          label="Warm-up equipment"
          value={mode}
          onChange={setMode}
          options={[
            { value: 'barbell', label: 'Barbell' },
            { value: 'increment', label: 'Dumbbell / machine' },
          ]}
        />
      </div>

      <div className="mb-4">
        <span className="rf-label">Warm-up sets</span>
        <Segmented
          label="Number of warm-up sets"
          value={setCount}
          onChange={setSetCount}
          options={[
            { value: '3', label: '3' },
            { value: '4', label: '4' },
            { value: '5', label: '5' },
          ]}
        />
      </div>

      {mode === 'barbell' ? (
        <div className="grid gap-3 sm:grid-cols-2">
          <Field label="Bar">
            {({ id }) => (
              <Select id={id} value={barId} onChange={(event) => setBarId(event.target.value)}>
                {bars.map((bar) => (
                  <option key={bar.id} value={bar.id}>
                    {bar.name}
                  </option>
                ))}
              </Select>
            )}
          </Field>
          <Field label="Plates">
            {({ id }) => (
              <Select
                id={id}
                value={inventoryId}
                onChange={(event) => setInventoryId(event.target.value)}
              >
                {inventories.map((inventory) => (
                  <option key={inventory.id} value={inventory.id}>
                    {inventory.name}
                  </option>
                ))}
              </Select>
            )}
          </Field>
        </div>
      ) : (
        <Field
          label={`Smallest load step (${weightUnit})`}
          hint="Dumbbell or machine increment. The plate calculator is not used for this equipment."
        >
          {({ id, describedBy }) => (
            <NumberInput
              id={id}
              aria-describedby={describedBy}
              value={incrementText}
              step="any"
              min={0}
              onChange={(event) => setIncrementText(event.target.value)}
            />
          )}
        </Field>
      )}

      {steps.length === 0 ? (
        <p className="rounded border border-line bg-surface-raised p-3 text-sm text-ink-muted">
          Enter a working weight to generate a ramp.
        </p>
      ) : (
        <>
          <ul className="space-y-1.5">
            {steps.map((step, index) => (
              <li
                key={`${step.weightG}-${index}`}
                className="flex items-center gap-2 rounded border border-line bg-surface-raised px-2 py-2"
              >
                <span className="w-7 text-center text-xs font-bold text-ink-subtle">
                  {index + 1}
                </span>
                <NumberInput
                  aria-label={`Warm-up ${index + 1} weight`}
                  className="h-10 w-24 min-h-0 px-2"
                  value={formatWeight(step.weightG, weightUnit)}
                  step="any"
                  min={0}
                  onChange={(event) => {
                    const value = Number.parseFloat(event.target.value.replace(',', '.'));
                    updateStep(index, {
                      weightG: Number.isFinite(value) ? toGrams(value, weightUnit) : 0,
                    });
                  }}
                />
                <span className="text-xs text-ink-subtle">{weightUnit}</span>
                <span aria-hidden="true" className="text-ink-subtle">
                  ×
                </span>
                <NumberInput
                  aria-label={`Warm-up ${index + 1} reps`}
                  className="h-10 w-16 min-h-0 px-2"
                  value={step.reps}
                  min={1}
                  inputMode="numeric"
                  onChange={(event) =>
                    updateStep(index, {
                      reps: Math.max(1, Number.parseInt(event.target.value, 10) || 1),
                    })
                  }
                />
                <span className="ml-auto text-xs text-ink-subtle">
                  {step.isBar ? 'bar' : `${Math.round(step.percent * 100)}%`}
                </span>
                <IconButton
                  label={`Remove warm-up set ${index + 1}`}
                  onClick={() => removeStep(index)}
                >
                  <Icon icon={Icons.trash} size={16} />
                </IconButton>
              </li>
            ))}
          </ul>

          <p className="mt-3 text-xs text-ink-subtle">
            Generated warm-ups are a loading convenience, not medical or coaching advice. Adjust
            anything that does not suit the movement or how you feel today.
          </p>

          {onInsert && (
            <Button variant="primary" block className="mt-3" onClick={() => onInsert(steps)}>
              {insertLabel}
            </Button>
          )}
        </>
      )}
    </div>
  );
}
